# Generated by Django 4.2.19 on 2025-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vacation_day_end_alter_vacation_day_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='user_info',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_info', to='users.tag', verbose_name='Теги'),
        ),
    ]
