# Generated by Django 4.2.19 on 2025-04-15 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_info_vacs_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель отдела'),
        ),
    ]
