# Generated by Django 4.2.19 on 2025-04-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_info_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='how_long',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего дней'),
        ),
    ]
