# Generated by Django 4.2.19 on 2025-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_vacation_can_redact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество'),
        ),
    ]
