# Generated by Django 4.2.19 on 2025-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vacation_type',
            field=models.CharField(blank=True, choices=[('UNPAID', 'Без содержания'), ('EXTRA', 'Дополнительный')], max_length=10, null=True, verbose_name='Тип отпуска'),
        ),
    ]
