# Generated by Django 4.2.19 on 2025-04-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tag_user_info_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='vacs_access',
        ),
    ]
