# Generated by Django 4.2.19 on 2025-04-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_unit_boss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'ordering': ('user',), 'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователях'},
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='boss',
        ),
    ]
