# Generated by Django 4.2.19 on 2025-04-15 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_info_options_remove_user_info_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_leaders', to=settings.AUTH_USER_MODEL, verbose_name='Вышестоящий руководитель'),
        ),
    ]
