# Generated by Django 4.2.19 on 2025-04-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_vacation_how_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='can_redact',
        ),
    ]
