# Generated by Django 4.2.19 on 2025-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('is_workday', models.BooleanField(default=False, help_text='✓ — рабочий, ☐ — нерабочий', verbose_name='Специальный рабочий день')),
            ],
            options={
                'verbose_name': 'Праздничный/рабочий день',
                'verbose_name_plural': 'Календарь',
                'ordering': ['date'],
            },
        ),
    ]
